camera_name: cam_test_1
camera_type: usb_camera
camera_fps: 30
frame_width: 640
frame_height: 480
is_used: 0
---
camera_name: cam_test_2
camera_type: usb_camera
camera_fps: 30
frame_width: 640
frame_height: 480
is_used: 0
---
camera_name: cam_test_3
camera_type: hik_camera_mv_cs016_10uc
camera_fps: 100
frame_width: 1440
frame_height: 1080
is_used: 0
---
camera_name: cam_test_4
camera_type: hik_camera_mv_ca013_21uc
camera_fps: 50
frame_width: 1280
frame_height: 1024
is_used: 0
---
camera_name: cam_test_5
camera_type: realsense_camera_d435i
camera_fps: 30
frame_width: 640
frame_height: 480
is_used: 0
